# fly.toml file generated for gemini on 2022-01-16T15:47:50-05:00

app = "gemini"

kill_signal = "SIGINT"
kill_timeout = 300
processes = []

[build]
  image = "registry.hub.docker.com/ninjapenguin/gemini-server:latest"

[deploy]
  strategy = "immediate"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/public"
