name:                gemini
version:             0.0.0.0
github:              "CharlesTaylor7/gemini"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2021 Charles Taylor"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/charlestaylor7/gemini#readme>

dependencies:
- base >= 4.14 && < 4.16
- relude
- text
- containers
- vector
- mtl
- optics >= 0.4
- prettyprinter
- jsaddle
- jsaddle-dom
- Shpadoinkle
- Shpadoinkle-html
- Shpadoinkle-lens
- random


default-extensions:
  # using relude instead
  - NoImplicitPrelude
  # together with optics solves the record problem
  - DuplicateRecordFields
  - OverloadedLabels
  - DataKinds
  - FlexibleContexts
  # conveniences
  - OverloadedStrings
  - ImportQualifiedPost
  - BlockArguments
  - NamedFieldPuns
  - PartialTypeSignatures
  - PatternSynonyms
  # deriving extensions
  - DerivingStrategies
  - DerivingVia
  - DeriveGeneric
  - DeriveAnyClass
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # misc
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - AllowAmbiguousTypes

ghc-options:
  # general
  - -ferror-spans
  - -freverse-errors
  # warnings
  - -Wall
  - -Wmissing-deriving-strategies
  - -Wmissing-signatures
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wtype-defaults
  - -Wunused-imports
  #- -Werror
  # turn off warnings
  - -Wno-name-shadowing
  - -Wno-partial-type-signatures


library:
  ghc-options:
    - -Wmissing-export-lists
  source-dirs: lib

executables:
  gemini:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gemini
    - Shpadoinkle-backend-pardiff


tests:
  gemini-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mars-rover
