name:                gemini
version:             0.0.0.0
github:              "CharlesTaylor7/gemini"
license:             BSD3
author:              "Charles Taylor"
maintainer:          "charlestaylor95@gmail.com"
copyright:           "2021 Charles Taylor"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/charlestaylor7/gemini#readme>

dependencies:
- base >= 4.14 && < 4.16
- relude
- text
- bytestring
- containers
- vector
- mtl
- optics >= 0.4
- prettyprinter
- random
- groups
- aeson
- jsaddle
- jsaddle-dom
- jsaddle-warp
- Shpadoinkle
- Shpadoinkle-html
- Shpadoinkle-lens
- Shpadoinkle-backend-pardiff


default-extensions:
  # using relude instead
  - NoImplicitPrelude
  # together with optics solves the record problem
  - DuplicateRecordFields
  - OverloadedLabels
  - DataKinds
  - FlexibleContexts
  # conveniences
  - OverloadedStrings
  - ImportQualifiedPost
  - BlockArguments
  - NamedFieldPuns
  - PartialTypeSignatures
  - PatternSynonyms
  # deriving extensions
  - DerivingStrategies
  - DerivingVia
  - DeriveGeneric
  - DeriveTraversable
  - DeriveAnyClass
  - GeneralizedNewtypeDeriving
  - StandaloneDeriving
  # misc
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - AllowAmbiguousTypes
  - ViewPatterns
  - PatternSynonyms
  - FlexibleInstances
  - MultiWayIf
  - MultiParamTypeClasses
  - ConstraintKinds

ghc-options:
  # general
  - -ferror-spans
  - -freverse-errors
  # warnings
  - -Wall
  - -Wmissing-deriving-strategies
  - -Wmissing-signatures
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wtype-defaults
  - -Wunused-imports
    #- -Werror
  # turn off warnings
  - -Wno-name-shadowing
  - -Wno-partial-type-signatures


library:
  ghc-options:
    - -Wmissing-export-lists
  source-dirs: src/lib

executables:
  server:
    main: Main.hs
    source-dirs: src/app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    dependencies:
    - gemini
  dev-server:
    main: Main.hs
    source-dirs: src/dev
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    dependencies:
    - gemini
    - rapid


tests:
  gemini-test:
    main: Spec.hs
    source-dirs: src/test
    ghc-options:
    - -threaded
    - -Wno-orphans
    dependencies:
    - QuickCheck
    - hspec
    - gemini
    verbatim: |
      build-tool-depends:
          hspec-discover:hspec-discover
