{ name = "gemini"
, dependencies =
  [ "aff"
  , "arrays"
  , "benchotron"
  , "console"
  , "control"
  , "datetime"
  , "debug"
  , "deku"
  , "effect"
  , "enums"
  , "filterable"
  , "foldable-traversable"
  , "hyrule"
  , "integers"
  , "lists"
  , "maybe"
  , "numbers"
  , "ordered-collections"
  , "partial"
  , "prelude"
  , "quickcheck"
  , "random"
  , "safe-coerce"
  , "spec"
  , "st"
  , "strings"
  , "tuples"
  , "unfoldable"
  , "unsafe-coerce"
  , "web-dom"
  , "web-events"
  , "web-uievents"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs", "benchmark/**/*.purs" ]
}
